# AMAZON AND UBUNTU STATUS:

- name: Verify Jenkins Services on (Amazon and Ubuntu)
  command: systemctl status jenkins
  changed_when: false
  when: ansible_distribution in ["Amazon","Ubuntu"]

- name: Verify Jenkins is listening on port 8080 on (Amazon and Ubuntu)
  wait_for: port=8080 timeout=8 delay=5
  when: ansible_distribution in ["Amazon","Ubuntu"]

- name: Check if Jenkins is accessible on (Amazon and Ubuntu)
  uri: url=http://127.0.0.1:8080/login?from=%2F method=GET status_code=200
  when: ansible_distribution in ["Amazon","Ubuntu"]

# MACOS STATUS:

- name: Verify Jenkins Service on (MacOSX Workstation)
  shell: brew services list | grep jenkins-lts
  changed_when: false
  when: ansible_distribution == "MacOSX"

- name: Verify Jenkins is listening on port 8080 on (MacOSX Workstation)
  wait_for: port=8080 timeout=8 delay=5
  when: ansible_distribution == "MacOSX"

- name: Check if Jenkins is accessible (MacOSX Workstation)
  uri: url=http://127.0.0.1:8080/login?from=%2F method=GET status_code=200
  when: ansible_distribution == "MacOSX"