---

- hosts: all
  become: true
  pre_tasks:                    # These tasks will be run before anything else in the playbook.
    - name: updates repo cache (Amazon Linux)
      tags: always
      dnf: update_cache=yes
      changed_when: false         # NOT A CHANGE NO MATTER WHAT - (WE WILL NOT SEE changed=1 IN THE PLAY RECAP)
      when: ansible_distribution == "Amazon"

    - name: updates repo cache (Ubuntu)
      tags: always
      apt: update_cache=yes
      changed_when: false         # NOT A CHANGE NO MATTER WHAT - - (WE WILL NOT SEE changed=1 IN THE PLAY RECAP)
      when: ansible_distribution == "Ubuntu"