---
- hosts: all
  become: true    # sudo permissions
  tasks:          # here we have multiple tasks in this playbook

    - name: Remove apache2 Package on Ubuntu Server
      package: name={{item}} state=absent update_cache=yes
      with_items:
        - apache2
        - libapache2-mod-php          # php support for apache if required for your project
        - libapache2-mod-wsgi-py3     # python3 support for apache if required for your project
      when: ansible_distribution == "Ubuntu"  


    - name: Remove httpd Package on Amazon Linux Server
      package: name={{item}} state=absent update_cache=yes
      with_items:
        - httpd
      when: ansible_distribution == "Amazon"
      