---
- hosts: all
  become: true    # sudo permissions
  tasks:          # here we have multiple tasks in this playbook

    - name: Install apache2 Package on Ubuntu Server
      package: name={{item}} state=latest update_cache=yes
      with_items:
        - apache2
        - libapache2-mod-php          # php support for apache if required for your project
        - libapache2-mod-wsgi-py3     # python3 support for apache if required for your project
      when: ansible_distribution == "Ubuntu"  


    - name: Install httpd Package on Amazon Linux Server
      package: name={{item}} state=latest update_cache=yes
      with_items:
        - httpd
      when: ansible_distribution == "Amazon"  
      

    - name: Ensure Apache2 Started on Ubuntu Server
      service: name=apache2 state=started enabled=yes
      when: ansible_distribution == "Ubuntu"


    - name: Ensure httpd Started on Amazon Linux Server
      service: name=httpd state=started enabled=yes
      when: ansible_distribution == "Amazon"
